# Book settings
title: "ICMS 2020 Session: The Jupyter Environment for Computational Mathematics"
author: Nicolas M. Thiéry et al.
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url                       : "https://github.com/nthiery/2020-07-13-ICMS-Jupyter"

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url             : "https://mybinder.org"
  thebelab                  : true

html:
  use_repository_button: true
  use_edit_page_button: true

execute:
  execute_notebooks: false

sphinx:
  extra_extensions:
    - sphinx_thebelab
